apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: scaffolding
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/scaffolding@sha256:1ed94bf5fd7de862ee9d660a25c978d35615755c4f684eb53e87242578d2dbf4
        name: my-go
        resources: {}
status: {}
