apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: scaffolding
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/scaffolding@sha256:3c3203ea337c2eb7dbcc88a333398ed8be565d27c19b856744c65163894ec90d
        name: my-go
        resources: {}
status: {}
