apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: scaffolding
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/scaffolding@sha256:4419c5650654194176ff505b628439b4e06dccee3e22c681467ef1139311b517
        name: my-go
        resources: {}
status: {}
