apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: scaffolding
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/scaffolding@sha256:8003b91b03bd7c12228ab663defc4eb93d055907f0f943abd362aa7976e44808
        name: my-go
        resources: {}
status: {}
