apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/ct-server@sha256:cf71ce8cb071b2914dbbd16cdaf8c9d0389fc69a107ee25ebefaa06b00590bba
        name: my-go
        resources: {}
status: {}
