apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/ct-server@sha256:e8d9f903bcc270e41e4586dc591a8bf002d9051301350b43d01c31b8593cfdd1
        name: my-go
        resources: {}
status: {}
