apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/ct-server@sha256:6748d9b80d202f3af168e752ffe308accec0e8c8b4e69fcd169fe663425d0f6c
        name: my-go
        resources: {}
status: {}
