apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/scaffolding/ct-server@sha256:e74d02c80a793b7253e8a205d750f214451029d0d678911041d6c53c1943cd6c
        name: my-go
        resources: {}
status: {}
