apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ct-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ct-server
    app.kubernetes.io/part-of: scaffolding
  name: ct-servernxtd
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ct-server
    weight: null
status: {}
